### ISSUE TITLE
Any license applied to your code?

### ISSUE THREAD

**Issue by karljaxon** [mgoltzsche/jenkins-jnlp-slave#2]
Hi Max,

No issue as such, but I would like to use your code! I'm trying to use the Jenkins docker plugin on a slave including podman and still encounter the same issues with 'docker top' and 'docker run' you've addressed in your script. Rather than writing a replacement 'docker' script I'd like to include yours. We redistribute our Jenkins setup to customers, so want to ensure you get any attribution you require (I don't see a license file in this repo). I was also wondering if you were thinking of making a release/putting down any tags?

Cheers,

Karl.

**Comment by mgoltzsche** [comment]
Hi @karljaxon,
thanks for asking! I've just applied the Apache-2.0 License to the project. I'd be happy if you'd link to this repository within your code but you don't have to.
I pushed the [v0.0.1](https://github.com/mgoltzsche/jenkins-jnlp-slave/releases/tag/v0.0.1) tag now. However please be aware that it still refers to container images using the `latest` tag which is why the build is still not reliably reproducible which I don't recommend in practice. Though you could refer to the `docker` workaround script reliably.
However, please note that I created this repo once as a proof of concept, just to show how this could be done. Therefore this project is not actively maintained.
